### PR TITLE
feature: add support for TS 5

### LINKED ISSUE #10: add support for TS 5
Currently, ts version is restricted in package.json

### PR DESCRIPTION
**Pull request by rbnayax**
fix: #10

### CODE REVIEW

**Comment by rbnayax** [comment]
@wessberg can you please CR? This blocks us from moving to TS5. Thanks :-)

**Comment by alvis** [comment]
@wessberg Today the typescript team has released 5.1. Hope this issue can be resolved soon.

**Comment by alvis** [comment]
ping @wessberg

**Comment by justinfagnani** [comment]
Sorry to add another ping, @wessberg. Would it help to take on @rbnayax as a maintainer?

**Comment by wessberg** [comment]
@rbnayax @justinfagnani

Thanks a lot for the PR, @rbnayax. I've looked into the changes, but there were a lot of changes related to formatting, so it was a little difficult to find the actual changes. I've configured the repo to run Prettier via `pretty-quick` and `husky` whenever you commit files, but the husky hooks only initialize after running `pnpm i`.

In any case, what was actually required to get full TS5 support was to implement handling for the new types of Nodes in TypeScript 5.0 and 5.1:

- JSDocSatisfiesTag
- JSDocOverloadTag
- JSDocThrowsTag
- JsxNamespacedName

I've gone ahead and implemented these separately from this PR and made sure the library is compliant with TS 5.1 in the meantime (published as [v3.0.0](https://github.com/wessberg/ts-clone-node/releases/tag/v3.0.0), so I'm afraid I can't merge this PR. But, feel free to contribute in the future, and thanks.

**Pull request closed without merging**
